### ISSUE TITLE
Stop after fail connection to AidBox

### ISSUE THREAD

**Issue by ir4y** [Aidbox/aidbox-python-sdk#8]
If an app can't connect to the AidBox, it should fail and stop working.
Now app continue working, so it accepts hooks requests from AidBox and fails in runtime.

**Comment by ruscoder** [comment]
This solution 81a432dd6d082869076fb00aa5878025d8c46571 works only when starting with gunicorn.  


Gunicorn has `--reload` flag and it can replace `adev runserver` for local development.  
Example:
```
gunicorn main:create_app --worker-class aiohttp.worker.GunicornWebWorker -b 0.0.0.0:8081 --reload
```
