### ISSUE TITLE
Handle unconnected state

### ISSUE THREAD

**Issue by ir4y** [Aidbox/aidbox-python-sdk#9]
1. When the app tries to connect to aidbox https://github.com/Aidbox/aidbox-python-sdk/blob/with-aidbox-py/aidbox_python_sdk/main.py#L52 it uses the default timeout.
In a kubernetes cluster, it gets a timeout for the first request and it takes about 5 minutes.
Let's restore timeout set to 3 seconds and fail if it reached https://github.com/Aidbox/aidbox-python-sdk/commit/670361da3489ed2f3606adae1a537c95fbf18737

2. In the proves of new deploy, It is possible that application gets a request from the AidBox but, it will not be initialized yet. In this case, SDK should respond to AidBox with 503 code, instead of a passing request to the handler.

**Comment by ruscoder** [comment]
Fixed in 666bb3037a27dd1033f6158cfe068adfc24a0340
